FROM eclipse-temurin:25-jdk
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        docker.io && \
    rm -rf /var/lib/apt/lists/*
ENV GRADLE_USER_HOME=/gradle-cache
RUN mkdir -p /gradle-cache && chmod 777 /gradle-cache
WORKDIR /app
RUN git config --system --add safe.directory /app
EXPOSE 8080
